### ISSUE TITLE
在debian下的node指令问题

### ISSUE THREAD

**Issue by zzliux** [weixin/node-lwip#1]
The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".
这个是README.debian的其中一段。是不是在debian下就只能手动nodejs prebuild了么

**Comment by littledu** [comment]
谢谢反馈，手头暂时没有 debian 环境测试一下，但从字面上看应该就是你说的意思，可以尝试把 nodejs 软链成 node，看下这个链接的处理方式：http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu
