### ISSUE TITLE
linux 下npm 安装wlip失败

### ISSUE THREAD

**Issue by win7killer** [weixin/node-lwip#3]
linux下安装失败     报错如下
**\* 是屏蔽掉的目录名

[root(0)@*****\* 17:01:57 /*****/node_img]# npm install lwip
npm WARN package.json node_img@1.0.0 No description
npm WARN package.json node_img@1.0.0 No repository field.
npm WARN package.json node_img@1.0.0 No README data
## npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.

> lwip@0.0.9 install /*****/node_img/node_modules/lwip
> node-gyp rebuild

make: Entering directory `/*****/node_img/node_modules/lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
make: g++：命令未找到
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] 错误 127
make: Leaving directory`/****_/node_img/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/**_********_/node-v4.4.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.el6.x86_64
gyp ERR! command "/**_********_/node-v4.4.4-linux-x64/bin/node" "/**_********_/node-v4.4.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /**_**/node_img/node_modules/lwip
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-573.el6.x86_64
npm ERR! argv "/************/node-v4.4.4-linux-x64/bin/node" "/usr/local/bin/npm" "install" "lwip"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /*****/node_img/npm-debug.log

**Comment by littledu** [comment]
貌似是需要的编译环境缺失，楼主试下运行：

```
npm install lwip 
```

看是否也有同样的问题

**Comment by zzliux** [comment]
先把gcc环境装上吧

**Comment by shanelau** [comment]
折腾了几个小时，切换 node 版本到 0.12 就安装成功了。

**Comment by littledu** [comment]
@shanelau 不是吧，linux 下？目前已经支持到node6了啊。

**Comment by shanelau** [comment]
@littledu mac 环境。安装了很多遍，切换到 node 6.9.1 安装成功了。主要就是图片处理库， c++ 编译报错
